### ISSUE TITLE
CTRL-U is shortcut for "undo last multicursor selection"

### ISSUE THREAD

**Issue by eduardoarandah** [noahcoad/open-url#33] opened 2016-08-20 19:48 UTC
CTRL-U is shortcut for "undo last multicursor selection" 

I don't think this is a good idea, because multicursor is a central feature for ST

How to change shortcut? I don't find it on the readme

**Comment by FichteFoll** [comment] 2016-10-24 00:54
+1, please address this significant issue. CTRL-U is a binding I use frequently and should certainly not be overwritten by any plugin.

@eduardoarandah, you need to override the ctrl+u binding in your User key bindings again.

```js
	{ "keys": ["ctrl+u"], "command": "soft_undo" },
```

**Comment by skylogic004** [comment] 2016-12-07 00:08
@FichteFoll thanks for the tip on overriding the key binding - exactly what I needed. I wish this plugin would have configurable hotkeys (though better would be to not override built-in hotkeys as mentioned)

**Comment by kpym** [comment] 2018-03-28 06:46
I want to advocate for this issue too. Please do not overwrite standard shortcuts. Thanks.

**Comment by kylebebak** [comment] 2018-08-09 16:14
I'll take care of this today!

**Comment by kylebebak** [comment] 2018-08-09 18:08
I just released 1.2.0, which changes the default key binding for the **open_url** command to <kbd>ctrl+alt+u</kbd> on Windows and Linux, which doesn't override any defaults on these platforms.

The key binding on OSX has not been changed, because <kbd>ctrl+u</kbd> doesn't override any defaults on OSX.

This is technically a breaking change, but I decided it was too small to justify a major version bump.

I'm going to close this, but I haven't been able to test on Linux or Windows, so please let me know if there are any problems.

**Closed by kylebebak** 2018-08-09 18:08 UTC

**Comment by skylogic004** [comment] 2018-08-09 20:30
Changes aren't showing up in sublime yet. Maybe you have to merge into st3 branch? (I'm not familiar with how Sublime works regarding git -- does it pull from master or from a branch?)

**Comment by kylebebak** [comment] 2018-08-09 21:16
@skylogic004 

I'll push to the ST3 branch and see if that works.

The versioning strategy for Open URL is currently `branches`. I have an open PR in [package_control_channel](https://github.com/wbond/package_control_channel/pulls) to change it to `tags`. With tags, the package automatically updates to the release with the "highest" tag.

I imagine it's not updating because of this.

**Comment by skylogic004** [comment] 2018-08-09 22:03
Thanks. I can confirm that ctrl+alt+u works on Windows now.
