### ISSUE TITLE
alt + double-click doesn't work on Mac OS

### ISSUE THREAD

**Issue by nicolashohm** [noahcoad/open-url#6] opened 2013-02-19 14:40 UTC
alt + double-click doesn't work on Mac OS, ctrl +u works perfect

**Comment by kylebebak** [comment] 2018-09-04 22:45
Can anyone repro this? It works fine in the latest release.

**Comment by leesei** [comment] 2018-09-05 10:15
Alas, recently Ctrl+U and Ctrl+Alt+U are not working (Sublime 3 on Arch Linux).
I can only trigger via right click menu.
Is there any debugging option to see if `open-url` received the `open_url` command?

**Comment by kylebebak** [comment] 2018-09-06 01:04
The default keymap for Linux and Windows looks like this:

```json
// Linux and Windows
[
	{ "keys": ["ctrl+alt+u"], "command": "open_url" }
]
```

So, `ctrl+alt+u` should work. The `ctrl+u` key binding was disabled on Linux and Windows, and will not be enabled in the future, because it conflicts with a default ST key binding. This isn't clear in the README. I've made an update to the README so that this is more clear.

To test if the command is being invoked, open the ST console and paste in the following: `sublime.log_commands(True)`. Then run Open URL using the hotkey, and check if **command: open_url** is printed to the console.

I think the most likely reason the key binding isn't working is that you have another identical key binding mapped to something else.

**Comment by leesei** [comment] 2018-09-06 04:05
Thanks for the reply, indeed I've added "ctrl+u" manually.

```
{ "keys": ["ctrl+u"], "command": "open_url", "args": { "show_menu": false } },
```

I can see `open_url` command triggered with both key binding.
```
command: open_url {"show_menu": false}   # ctrl+u
command: open_url                        # ctrl+alt+u
```
But the browser is not triggered.

I tried to change the "web_browser" setting to "google-chrome" but there is a pop up saying
```
```

**Comment by kylebebak** [comment] 2018-09-06 14:43
I see that both "chrome" and "google-chrome" are options [on this list](https://docs.python.org/3.3/library/webbrowser.html).

Have you tried setting your `web_browser` to "chrome"? That might help, but I sort of doubt it.

I'm not sure the `webbrowser` library works, but based on what you're saying it seems like it just tries to look up an executable based on one of the browser strings it that list.

There's not currently a way to set a path or a shell command for opening a browser, so I'll add one. But I'm not sure which API to use.

I did some research, and found two ways to set a path to an executable for opening a browser using `webbrowser`:

[The way you've listed above](https://stackoverflow.com/questions/48056052/webbrowser-get-could-not-locate-runnable-browser).

[And this way](https://stackoverflow.com/questions/22445217/python-webbrowser-open-to-open-chrome-browser):

~~~py
# MacOS
chrome_path = 'open -a /Applications/Google\ Chrome.app %s'

# Windows
# chrome_path = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s'

# Linux
# chrome_path = '/usr/bin/google-chrome %s'

webbrowser.get(chrome_path).open('http://google.com')
~~~

I think I prefer the second API, in part because the first one doesn't work on OSX! The second one does, and I figure it should work on Linux as well. Could you try it, i.e. try the following?

~~~py
chrome_path = '/usr/bin/google-chrome-stable %s'
webbrowser.get(chrome_path).open('http://google.com')
~~~

If this works, I'll add a `web_browser_path` setting, you can put ```"web_browser_path": "/usr/bin/google-chrome-stable %s"``` in settings and we'll call it a day.

**Comment by leesei** [comment] 2018-09-07 02:45
I've tried setting "web_browser" to "chrome" and "google_chrome", both have the "couldn't find" popup. 

This worked like charm:
```
chrome_path = '/usr/bin/google-chrome-stable %s'
webbrowser.get(chrome_path).open('http://google.com')
```

So are your replacing "web_browser" with "web_browser_path"? The latter seems more reliable than the webbrowser module.
Thanks for the support.

---

@nickel715, sorry for hijacking this issue. I'm not sure if it is the cause of the issue you reported in the first place. 
On second thought, Alt+Mouse click/drag might be reserved by desktop manager in X11 for moving the windows. So this combo might fail for Linux platform, I'm not using this combo personally.

**Comment by leesei** [comment] 2018-09-07 02:57
I checked the implementation of webbrowser:
https://github.com/python/cpython/blob/3.3/Lib/webbrowser.py#L453

It was checking a list of hardcoded binary name and registering them if they are executable in `$PATH`, needless to say `google-chrome-stable` is not in the list.
Maybe I'll have to restart to make the symlink to work.

Also setting "web_browser" to "xdg-open" worked for me as `google-chrome-stable` is registered to my desktop environment.
Maybe add a comment like this to "web_browser" is enough, without the need to change code:
```
If the Python `webbrowser` package failed to pick up the your on Linux environment, try setting "web_browser" to "xdg-open" to let your desktop environment to handle the URL.
```

**Comment by kylebebak** [comment] 2018-09-07 13:16
Cool, I'll push the change. I didn't replace `web_browser` with `web_browser_path`. I added the `web_browser_path` setting, and it overrides `web_browser` if both are specified.

I included examples for OSX, Windows and Linux in the default settings file. The relevant part looks like this:

~~~json
  // the browser that Open URL uses to open new tabs
  // it can be an empty string, or a string [from this list](https://docs.python.org/3.3/library/webbrowser.html)
  "web_browser": "",

  // the path to the executable that Open URL uses to open new tabs; overrides "web_browser"
  "web_browser_path": "",
  // example: chrome, osx
  // "web_browser_path": "open -a /Applications/Google\\ Chrome.app %s"
  // example: chrome, windows
  // "web_browser_path": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s"
  // example: chrome, linux
  // "web_browser_path": "/usr/bin/google-chrome %s"
~~~

@nickel715 
Maybe it's like leesei says, and you have some other mouse/key binding that's overriding <kbd>alt+double-click</kbd>.

This issue did get hijacked, so I'm not going to close it until I add info to the docs about overriding **Default.sublime-mousemap** bindings.

@leesei 
Please let me know if setting `web_browser_path` works for you!

**Closed as completed** 2018-09-07 13:23 UTC

**Comment by leesei** [comment] 2018-09-10 03:26
`web_browser_path` works great. Thanks.

**Comment by kylebebak** [comment] 2018-09-10 15:08
Right on =)
