### ISSUE TITLE
File path selections break when using line select

### ISSUE THREAD

**Issue by Deadpool13** [noahcoad/open-url#8] opened 2013-03-06 19:44 UTC
I noticed when clicking the line number to select a path via its corresponding line, versus manually dragging to select with the mouse, OpenURL will open in the browser as a search rather than opening the correct folder in Explorer. I'm guessing this has to do with the line break at the end from selecting via the line #. Is there a way to null out the line break behavior so it works properly with this selection method? Would be a lot handier if you didn't have to select manually with the mouse drag like that. Also I noted that it only does this behavior when there actually is a next line (allowing for the break at the end). If you use this selection method on a link that's at the end of a document it opens in Explorer as intended.

**Comment by kylebebak** [comment] 2018-08-09 16:19
Should be fixed from 1.1.0 onward, can't reproduce now. Reopen if issue persists.

**Closed by kylebebak** 2018-08-09 16:19 UTC
